/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const FeedbackEntry = IDL.Record({
  'age' : IDL.Nat,
  'description' : IDL.Text,
  'gender' : IDL.Text,
  'timestamp' : Time,
  'disease' : IDL.Text,
  'rating' : IDL.Nat,
});
export const ImageUpload = IDL.Record({
  'status' : IDL.Text,
  'filename' : IDL.Text,
  'timestamp' : Time,
});
export const PlatformStats = IDL.Record({
  'totalAnalyses' : IDL.Nat,
  'accuracy' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addContactSubmission' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'addImageUpload' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getFeedbacks' : IDL.Func([], [IDL.Vec(FeedbackEntry)], ['query']),
  'getImageUploadByFilename' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ImageUpload)],
      ['query'],
    ),
  'getImageUploads' : IDL.Func([], [IDL.Vec(ImageUpload)], ['query']),
  'getStats' : IDL.Func([], [IDL.Opt(PlatformStats)], ['query']),
  'submitFeedback' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateStats' : IDL.Func([IDL.Nat, IDL.Float64], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const FeedbackEntry = IDL.Record({
    'age' : IDL.Nat,
    'description' : IDL.Text,
    'gender' : IDL.Text,
    'timestamp' : Time,
    'disease' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const ImageUpload = IDL.Record({
    'status' : IDL.Text,
    'filename' : IDL.Text,
    'timestamp' : Time,
  });
  const PlatformStats = IDL.Record({
    'totalAnalyses' : IDL.Nat,
    'accuracy' : IDL.Float64,
  });
  
  return IDL.Service({
    'addContactSubmission' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'addImageUpload' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getFeedbacks' : IDL.Func([], [IDL.Vec(FeedbackEntry)], ['query']),
    'getImageUploadByFilename' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ImageUpload)],
        ['query'],
      ),
    'getImageUploads' : IDL.Func([], [IDL.Vec(ImageUpload)], ['query']),
    'getStats' : IDL.Func([], [IDL.Opt(PlatformStats)], ['query']),
    'submitFeedback' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateStats' : IDL.Func([IDL.Nat, IDL.Float64], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };